name: 'AppCatalog Upload'
description: 'Uploads an iOS or android App to the adorsys AppCatalog'
author: 'adorsys GmbH & Co. KG'
inputs:
  tenantId:
    description: 'Id of the Tenant'
    required: true
  appId:
    description: 'Id of the App'
    required: true
  filePath:
    description: 'Path to the .ipa or .apk file'
    required: true
  releaseNotes:
    description: 'Release notes for the App version that will be uploaded'
    default: ''
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
